locals {
  // Ported location pairs from Bicep
  location_pairs = {
    canadacentral      = "centralus"
    canadaeast         = "canadacentral"
    centralus          = "eastus"
    eastus             = "centralus"
    eastus2            = "centralus"
    northcentralus     = "centralus"
    southcentralus     = "westus"
    westcentralus      = "westus"
    westus             = "westus2"
    westus2            = "westus"
    westus3            = "westus2"
    brazilsouth        = "brazilsoutheast"
    brazilsoutheast    = "brazilsouth"
    francecentral      = "westeurope"
    francesouth        = "francecentral"
    germanynorth       = "northeurope"
    germanywestcentral = "germanynorth"
    italynorth         = "francecentral"
    northeurope        = "westeurope"
    norwayeast         = "northeurope"
    norwaywest         = "northeurope"
    polandcentral      = "northeurope"
    southuk            = "westeurope"
    uksouth            = "westeurope"
    spaincentral       = "francecentral"
    swedencentral      = "northeurope"
    swedensouth        = "swedencentral"
    switzerlandnorth   = "westeurope"
    switzerlandwest    = "westeurope"
    westeurope         = "northeurope"
    westuk             = "southuk"
    ukwest             = "uksouth"
    qatarcentral       = "uaecentral"
    uaecentral         = "uaenorth"
    uaenorth           = "qatarcentral"
    centralindia       = "southindia"
    southindia         = "centralindia"
    eastasia           = "southeastasia"
    japaneast          = "japanwest"
    japanwest          = "japaneast"
    koreacentral       = "koreasouth"
    koreasouth         = "koreacentral"
    southeastasia      = "eastasia"
    australiacentral   = "australiaeast"
    australiacentral2  = "australiacentral"
    australiaeast      = "australiasoutheast"
    australiasoutheast = "australiaeast"
    southafricanorth   = "southafricawest"
    southafricawest    = "southafricanorth"
  }

  effective_replication_location = coalesce(var.replication_location, lookup(local.location_pairs, lower(var.location), null))
}
